# Generated by Django 4.1.1 on 2022-09-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('Transfer Degree', 'Transfer Degree'), ('Doctoral Degree', 'Doctoral Degree'), ('Graduate Degrees', 'Graduate Degrees'), ('Undergraduate Degrees', 'Undergraduate Degrees'), ('Master Degree', 'Master Degree'), ('Bachelor Degree', 'Bachelor Degree'), ('Associate Degree', 'Associate Degree'), ('Professional Degree', 'Professional Degree'), ('Professional Certificate', 'Professional Certificate'), ('Specialist Degree', 'Specialist Degree')], max_length=100, null=True, verbose_name='degree'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single ', 'Single '), ('Engaged', 'Engaged'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Widower', 'Widower'), ('Unknown', 'Unknown')], max_length=100, null=True, verbose_name='marital_status'),
        ),
    ]
